### ISSUE TITLE
Lazy loading the language files

### ISSUE THREAD

**Issue by sebastiaan-de-vries** [FrontLabsOfficial/vue-i18n-lite#4]
Hi there!

I stumbled upon your project while looking for a lightweight solution for i18n for our Vue application. The bundle size of your lib is awesome, but now my translations (we have over 50 languages to support) are still very big. I was wondering if lazy loading the translations files is something that would be difficult to build in.

I can imagine that this feature is useful especially for people using this lightweight lib, as their are concerned with shipping as little kilobytes as possible.

I would be interested in helping out with this, but I have not yet created a PR or written a Vue plugin before, so I might need some guidance with this. I would be interested in your thoughts on this!

Kind regards,
Sebastiaan

**Comment by niutech** [comment]
You could achieve it like this:
```js
import en from './en.json'
const i18n = createI18n({
    locale: 'en',
    fallbackLocale: 'en',
    messages: { en }
})
async function setLocale(locale) {
    const message = i18n.getLocaleMessage(locale)
    if (!Object.keys(message).length) {
        const { default: message } = await import('./' + locale + '.json')
        i18n.setLocaleMessage(locale, message)
    }
    i18n.changeLocale(locale)
}
setLocale('es')
```

**Comment by sebastiaan-de-vries** [comment]
Thank you very much, that works great!
